stages:
  - build
  - package
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build

package:
  stage: package
  script:
    - npm run package-live

deploy:
  stage: deploy
  script:
    - # Add deployment commands here