name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: npm install
        run: |
          npm install
          npm run postinstall
          npm run build

      - name: npm test
        run: |
          npm run package-live
          npm exec electron-builder -- --publish always --win